/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpCenterRouteImport } from './routes/help-center'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EngineerUserIdRouteImport } from './routes/engineer.$userId'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedInterviewRouteImport } from './routes/_authenticated/interview'
import { Route as AuthenticatedHireRouteImport } from './routes/_authenticated/hire'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApplyRouteImport } from './routes/_authenticated/apply'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedRequestsRequestIdRouteImport } from './routes/_authenticated/requests.$requestId'
import { Route as AuthenticatedJobsJobIdRouteImport } from './routes/_authenticated/jobs.$jobId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterRoute = HelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerUserIdRoute = EngineerUserIdRouteImport.update({
  id: '/engineer/$userId',
  path: '/engineer/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInterviewRoute = AuthenticatedInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHireRoute = AuthenticatedHireRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplyRoute = AuthenticatedApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRequestsRequestIdRoute =
  AuthenticatedRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobsJobIdRoute = AuthenticatedJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help-center': typeof HelpCenterRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/apply': typeof AuthenticatedApplyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hire': typeof AuthenticatedHireRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/engineer/$userId': typeof EngineerUserIdRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help-center': typeof HelpCenterRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/apply': typeof AuthenticatedApplyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hire': typeof AuthenticatedHireRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/engineer/$userId': typeof EngineerUserIdRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/help-center': typeof HelpCenterRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/apply': typeof AuthenticatedApplyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hire': typeof AuthenticatedHireRoute
  '/_authenticated/interview': typeof AuthenticatedInterviewRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/engineer/$userId': typeof EngineerUserIdRoute
  '/_authenticated/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/_authenticated/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help-center'
    | '/login'
    | '/network'
    | '/signup'
    | '/admin'
    | '/apply'
    | '/dashboard'
    | '/hire'
    | '/interview'
    | '/roles'
    | '/engineer/$userId'
    | '/jobs/$jobId'
    | '/requests/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help-center'
    | '/login'
    | '/network'
    | '/signup'
    | '/admin'
    | '/apply'
    | '/dashboard'
    | '/hire'
    | '/interview'
    | '/roles'
    | '/engineer/$userId'
    | '/jobs/$jobId'
    | '/requests/$requestId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/help-center'
    | '/login'
    | '/network'
    | '/signup'
    | '/_authenticated/admin'
    | '/_authenticated/apply'
    | '/_authenticated/dashboard'
    | '/_authenticated/hire'
    | '/_authenticated/interview'
    | '/_authenticated/roles'
    | '/engineer/$userId'
    | '/_authenticated/jobs/$jobId'
    | '/_authenticated/requests/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HelpCenterRoute: typeof HelpCenterRoute
  LoginRoute: typeof LoginRoute
  NetworkRoute: typeof NetworkRoute
  SignupRoute: typeof SignupRoute
  EngineerUserIdRoute: typeof EngineerUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center': {
      id: '/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/$userId': {
      id: '/engineer/$userId'
      path: '/engineer/$userId'
      fullPath: '/engineer/$userId'
      preLoaderRoute: typeof EngineerUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interview': {
      id: '/_authenticated/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof AuthenticatedInterviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hire': {
      id: '/_authenticated/hire'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof AuthenticatedHireRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apply': {
      id: '/_authenticated/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof AuthenticatedApplyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests/$requestId': {
      id: '/_authenticated/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof AuthenticatedRequestsRequestIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs/$jobId': {
      id: '/_authenticated/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedApplyRoute: typeof AuthenticatedApplyRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHireRoute: typeof AuthenticatedHireRoute
  AuthenticatedInterviewRoute: typeof AuthenticatedInterviewRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedJobsJobIdRoute: typeof AuthenticatedJobsJobIdRoute
  AuthenticatedRequestsRequestIdRoute: typeof AuthenticatedRequestsRequestIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedApplyRoute: AuthenticatedApplyRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHireRoute: AuthenticatedHireRoute,
  AuthenticatedInterviewRoute: AuthenticatedInterviewRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedJobsJobIdRoute: AuthenticatedJobsJobIdRoute,
  AuthenticatedRequestsRequestIdRoute: AuthenticatedRequestsRequestIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HelpCenterRoute: HelpCenterRoute,
  LoginRoute: LoginRoute,
  NetworkRoute: NetworkRoute,
  SignupRoute: SignupRoute,
  EngineerUserIdRoute: EngineerUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
