/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResumeReviewRouteImport } from './routes/resume-review'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OpenRolesRouteImport } from './routes/open-roles'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpCenterRouteImport } from './routes/help-center'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as DataPartnershipsRouteImport } from './routes/data-partnerships'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EngineerUserIdRouteImport } from './routes/engineer.$userId'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedReferRouteImport } from './routes/_authenticated/refer'
import { Route as AuthenticatedInterviewRouteImport } from './routes/_authenticated/interview'
import { Route as AuthenticatedHireRouteImport } from './routes/_authenticated/hire'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApplyRouteImport } from './routes/_authenticated/apply'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedRequestsRequestIdRouteImport } from './routes/_authenticated/requests.$requestId'
import { Route as AuthenticatedJobsJobIdRouteImport } from './routes/_authenticated/jobs.$jobId'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeReviewRoute = ResumeReviewRouteImport.update({
  id: '/resume-review',
  path: '/resume-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenRolesRoute = OpenRolesRouteImport.update({
  id: '/open-roles',
  path: '/open-roles',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterRoute = HelpCenterRouteImport.update({
  id: '/help-center',
  path: '/help-center',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const DataPartnershipsRoute = DataPartnershipsRouteImport.update({
  id: '/data-partnerships',
  path: '/data-partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineerUserIdRoute = EngineerUserIdRouteImport.update({
  id: '/engineer/$userId',
  path: '/engineer/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReferRoute = AuthenticatedReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInterviewRoute = AuthenticatedInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHireRoute = AuthenticatedHireRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplyRoute = AuthenticatedApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRequestsRequestIdRoute =
  AuthenticatedRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobsJobIdRoute = AuthenticatedJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/data-partnerships': typeof DataPartnershipsRoute
  '/enterprise': typeof EnterpriseRoute
  '/help-center': typeof HelpCenterRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/open-roles': typeof OpenRolesRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/resume-review': typeof ResumeReviewRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/apply': typeof AuthenticatedApplyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hire': typeof AuthenticatedHireRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/refer': typeof AuthenticatedReferRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/engineer/$userId': typeof EngineerUserIdRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/data-partnerships': typeof DataPartnershipsRoute
  '/enterprise': typeof EnterpriseRoute
  '/help-center': typeof HelpCenterRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/open-roles': typeof OpenRolesRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/resume-review': typeof ResumeReviewRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/apply': typeof AuthenticatedApplyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hire': typeof AuthenticatedHireRoute
  '/interview': typeof AuthenticatedInterviewRoute
  '/refer': typeof AuthenticatedReferRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/workspace': typeof AuthenticatedWorkspaceRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/engineer/$userId': typeof EngineerUserIdRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/data-partnerships': typeof DataPartnershipsRoute
  '/enterprise': typeof EnterpriseRoute
  '/help-center': typeof HelpCenterRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/open-roles': typeof OpenRolesRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/resume-review': typeof ResumeReviewRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/stories': typeof StoriesRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/apply': typeof AuthenticatedApplyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hire': typeof AuthenticatedHireRoute
  '/_authenticated/interview': typeof AuthenticatedInterviewRoute
  '/_authenticated/refer': typeof AuthenticatedReferRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/engineer/$userId': typeof EngineerUserIdRoute
  '/_authenticated/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/_authenticated/requests/$requestId': typeof AuthenticatedRequestsRequestIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/careers'
    | '/data-partnerships'
    | '/enterprise'
    | '/help-center'
    | '/login'
    | '/network'
    | '/open-roles'
    | '/privacy'
    | '/resources'
    | '/resume-review'
    | '/security'
    | '/signup'
    | '/stories'
    | '/terms'
    | '/unsubscribe'
    | '/admin'
    | '/apply'
    | '/dashboard'
    | '/hire'
    | '/interview'
    | '/refer'
    | '/roles'
    | '/workspace'
    | '/email/unsubscribe'
    | '/engineer/$userId'
    | '/jobs/$jobId'
    | '/requests/$requestId'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/careers'
    | '/data-partnerships'
    | '/enterprise'
    | '/help-center'
    | '/login'
    | '/network'
    | '/open-roles'
    | '/privacy'
    | '/resources'
    | '/resume-review'
    | '/security'
    | '/signup'
    | '/stories'
    | '/terms'
    | '/unsubscribe'
    | '/admin'
    | '/apply'
    | '/dashboard'
    | '/hire'
    | '/interview'
    | '/refer'
    | '/roles'
    | '/workspace'
    | '/email/unsubscribe'
    | '/engineer/$userId'
    | '/jobs/$jobId'
    | '/requests/$requestId'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/blog'
    | '/careers'
    | '/data-partnerships'
    | '/enterprise'
    | '/help-center'
    | '/login'
    | '/network'
    | '/open-roles'
    | '/privacy'
    | '/resources'
    | '/resume-review'
    | '/security'
    | '/signup'
    | '/stories'
    | '/terms'
    | '/unsubscribe'
    | '/_authenticated/admin'
    | '/_authenticated/apply'
    | '/_authenticated/dashboard'
    | '/_authenticated/hire'
    | '/_authenticated/interview'
    | '/_authenticated/refer'
    | '/_authenticated/roles'
    | '/_authenticated/workspace'
    | '/email/unsubscribe'
    | '/engineer/$userId'
    | '/_authenticated/jobs/$jobId'
    | '/_authenticated/requests/$requestId'
    | '/lovable/email/suppression'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  DataPartnershipsRoute: typeof DataPartnershipsRoute
  EnterpriseRoute: typeof EnterpriseRoute
  HelpCenterRoute: typeof HelpCenterRoute
  LoginRoute: typeof LoginRoute
  NetworkRoute: typeof NetworkRoute
  OpenRolesRoute: typeof OpenRolesRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  ResumeReviewRoute: typeof ResumeReviewRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  StoriesRoute: typeof StoriesRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  EngineerUserIdRoute: typeof EngineerUserIdRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-review': {
      id: '/resume-review'
      path: '/resume-review'
      fullPath: '/resume-review'
      preLoaderRoute: typeof ResumeReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-roles': {
      id: '/open-roles'
      path: '/open-roles'
      fullPath: '/open-roles'
      preLoaderRoute: typeof OpenRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center': {
      id: '/help-center'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof HelpCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-partnerships': {
      id: '/data-partnerships'
      path: '/data-partnerships'
      fullPath: '/data-partnerships'
      preLoaderRoute: typeof DataPartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineer/$userId': {
      id: '/engineer/$userId'
      path: '/engineer/$userId'
      fullPath: '/engineer/$userId'
      preLoaderRoute: typeof EngineerUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/refer': {
      id: '/_authenticated/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof AuthenticatedReferRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interview': {
      id: '/_authenticated/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof AuthenticatedInterviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hire': {
      id: '/_authenticated/hire'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof AuthenticatedHireRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apply': {
      id: '/_authenticated/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof AuthenticatedApplyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/requests/$requestId': {
      id: '/_authenticated/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/requests/$requestId'
      preLoaderRoute: typeof AuthenticatedRequestsRequestIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs/$jobId': {
      id: '/_authenticated/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedApplyRoute: typeof AuthenticatedApplyRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHireRoute: typeof AuthenticatedHireRoute
  AuthenticatedInterviewRoute: typeof AuthenticatedInterviewRoute
  AuthenticatedReferRoute: typeof AuthenticatedReferRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRoute
  AuthenticatedJobsJobIdRoute: typeof AuthenticatedJobsJobIdRoute
  AuthenticatedRequestsRequestIdRoute: typeof AuthenticatedRequestsRequestIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedApplyRoute: AuthenticatedApplyRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHireRoute: AuthenticatedHireRoute,
  AuthenticatedInterviewRoute: AuthenticatedInterviewRoute,
  AuthenticatedReferRoute: AuthenticatedReferRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRoute,
  AuthenticatedJobsJobIdRoute: AuthenticatedJobsJobIdRoute,
  AuthenticatedRequestsRequestIdRoute: AuthenticatedRequestsRequestIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  DataPartnershipsRoute: DataPartnershipsRoute,
  EnterpriseRoute: EnterpriseRoute,
  HelpCenterRoute: HelpCenterRoute,
  LoginRoute: LoginRoute,
  NetworkRoute: NetworkRoute,
  OpenRolesRoute: OpenRolesRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  ResumeReviewRoute: ResumeReviewRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  StoriesRoute: StoriesRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  EngineerUserIdRoute: EngineerUserIdRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
